server:
  port: 8005

spring:
  cloud:
    config:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
          isolation:
            thread:
              timeoutInMilliseconds: 4000

HELLO-SERVICE: # name from @FeignClient
  ribbon:
#    ConnectTimeout: 500
    ReadTimeout: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1

# hystrix time limitation will trigger fallback after timeout.
# ribbon config will retry read until the response time not reach the ReadTimeout.

