server:
  port: 8003

spring:
  application:
    name: ribbon-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream
