server:
  port: 8002

spring:
  application:
    name: hello-service-backup

spring:
  cloud:
    config:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

