server:
  port: 8001

spring:
  application:
    name: hello-service

spring:
  cloud:
    config:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

