server:
  port: 8006

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/

zuul:
  routes:
    api-a:
      path: /feign-consumer/**
    api-a:
      serviceId: feign-consumer
    api-b:
      path: /ribbin-consumer/**
    api-b:
      serviceId: ribbin-consumer
    api-c:
      path: /hystrix-dashboard/**
    api-c:
      serviceId: hystrix-dashboard

zuul:
  ignored-services:
    - hello-service

